### ISSUE TITLE
Init development of client

### ISSUE THREAD

**Issue by antonlin1** [antonlin1/cplusplus_programming#2]
From the project description: 
- The clients reads commands from the keyboard, communicates with the server and presents the replies from the server on the terminal.
- The client is easy to use and contains informative help texts. No manual is necessary to use the client program.
- The client tries to handle all errors. If it cannot recover from an error, it terminates with an informative error message.

**Comment by antonlin1** [comment]
BTW, feel free to unassign. I'm just assigning the shit out of this so people gets notified

**Comment by HampusBalldin** [comment]
I will work on the client now.
